/**
 * This file is generated by the update-css script. Do not edit this file directly. Instead, edit the script and run it
 * again.
 */
export const COLOR_VARIANTS = [
    'grey',
    'white',
    'primary',
    'secondary',
    'blue',
    'green',
    'lime',
    'magenta',
    'orange',
    'pink',
    'purple',
    'red',
    'teal',
    'yellow',
] as const;
export type ColorVariant = (typeof COLOR_VARIANTS)[number];
