/* eslint-disable @cspell/spellchecker */
import { CountryCode } from 'libphonenumber-js';

export type SupportedCountryCode = keyof CountryCodeData;

export type CountryCodeData = Omit<
    Record<CountryCode, { name: string }>,
    | 'AC'
    | 'CI'
    | 'CV'
    | 'FM'
    | 'GP'
    | 'KN'
    | 'LC'
    | 'MF'
    | 'NC'
    | 'RE'
    | 'SH'
    | 'SJ'
    | 'TA'
    | 'VA'
    | 'VC'
    | 'WF'
    | 'XK'
    | 'YT'
>;

export const countryCodeData: CountryCodeData = {
    AD: { name: 'Andorra' },
    AE: { name: 'United Arab Emirates' },
    AF: { name: 'Afghanistan' },
    AG: { name: 'Antigua and Barbuda' },
    AI: { name: 'Anguilla' },
    AL: { name: 'Albania' },
    AM: { name: 'Armenia' },
    AO: { name: 'Angola' },
    AR: { name: 'Argentina' },
    AS: { name: 'American Samoa' },
    AT: { name: 'Austria' },
    AU: { name: 'Australia' },
    AW: { name: 'Aruba' },
    AX: { name: 'Åland Islands' },
    AZ: { name: 'Azerbaijan' },
    BA: { name: 'Bosnia and Herzegovina' },
    BB: { name: 'Barbados' },
    BD: { name: 'Bangladesh' },
    BE: { name: 'Belgium' },
    BF: { name: 'Burkina Faso' },
    BG: { name: 'Bulgaria' },
    BH: { name: 'Bahrain' },
    BI: { name: 'Burundi' },
    BJ: { name: 'Benin' },
    BL: { name: 'Saint Barthélemy' },
    BM: { name: 'Bermuda' },
    BN: { name: 'Brunei' },
    BO: { name: 'Bolivia' },
    BQ: { name: 'Bonaire, Sint Eustatius and Saba' },
    BR: { name: 'Brazil' },
    BS: { name: 'Bahamas' },
    BT: { name: 'Bhutan' },
    BW: { name: 'Botswana' },
    BY: { name: 'Belarus' },
    BZ: { name: 'Belize' },
    CA: { name: 'Canada' },
    CC: { name: 'Cocos (Keeling) Islands' },
    CD: { name: 'Democratic Republic of the Congo' },
    CF: { name: 'Central African Republic' },
    CG: { name: 'Republic of the Congo' },
    CH: { name: 'Switzerland' },
    // CI: { name: "Ivory Coast" },
    CK: { name: 'Cook Islands' },
    CL: { name: 'Chile' },
    CM: { name: 'Cameroon' },
    CN: { name: 'China' },
    CO: { name: 'Colombia' },
    CR: { name: 'Costa Rica' },
    CU: { name: 'Cuba' },
    // CV: { name: "Cape Verde" },
    CW: { name: 'Curaçao' },
    CX: { name: 'Christmas Island' },
    CY: { name: 'Cyprus' },
    CZ: { name: 'Czech Republic' },
    DE: { name: 'Germany' },
    DJ: { name: 'Djibouti' },
    DK: { name: 'Denmark' },
    DM: { name: 'Dominica' },
    DO: { name: 'Dominican Republic' },
    DZ: { name: 'Algeria' },
    EC: { name: 'Ecuador' },
    EE: { name: 'Estonia' },
    EG: { name: 'Egypt' },
    EH: { name: 'Western Sahara' },
    ER: { name: 'Eritrea' },
    ES: { name: 'Spain' },
    ET: { name: 'Ethiopia' },
    FI: { name: 'Finland' },
    FJ: { name: 'Fiji' },
    FK: { name: 'Falkland Islands' },
    // FM: { name: "Micronesia" },
    FO: { name: 'Faroe Islands' },
    FR: { name: 'France' },
    GA: { name: 'Gabon' },
    GB: { name: 'United Kingdom' },
    GD: { name: 'Grenada' },
    GE: { name: 'Georgia' },
    GF: { name: 'French Guiana' },
    GG: { name: 'Guernsey' },
    GH: { name: 'Ghana' },
    GI: { name: 'Gibraltar' },
    GL: { name: 'Greenland' },
    GM: { name: 'Gambia' },
    GN: { name: 'Guinea' },
    // GP: { name: "Guadeloupe" },
    GQ: { name: 'Equatorial Guinea' },
    GR: { name: 'Greece' },
    GT: { name: 'Guatemala' },
    GU: { name: 'Guam' },
    GW: { name: 'Guinea-Bissau' },
    GY: { name: 'Guyana' },
    HK: { name: 'Hong Kong' },
    HN: { name: 'Honduras' },
    HR: { name: 'Croatia' },
    HT: { name: 'Haiti' },
    HU: { name: 'Hungary' },
    ID: { name: 'Indonesia' },
    IE: { name: 'Ireland' },
    IL: { name: 'Israel' },
    IM: { name: 'Isle of Man' },
    IN: { name: 'India' },
    IO: { name: 'British Indian Ocean Territory' },
    IQ: { name: 'Iraq' },
    IR: { name: 'Iran' },
    IS: { name: 'Iceland' },
    IT: { name: 'Italy' },
    JE: { name: 'Jersey' },
    JM: { name: 'Jamaica' },
    JO: { name: 'Jordan' },
    JP: { name: 'Japan' },
    KE: { name: 'Kenya' },
    KG: { name: 'Kyrgyzstan' },
    KH: { name: 'Cambodia' },
    KI: { name: 'Kiribati' },
    KM: { name: 'Comoros' },
    // KN: { name: "Saint Kitts and Nevis" },
    KP: { name: 'North Korea' },
    KR: { name: 'South Korea' },
    KW: { name: 'Kuwait' },
    KY: { name: 'Cayman Islands' },
    KZ: { name: 'Kazakhstan' },
    LA: { name: 'Laos' },
    LB: { name: 'Lebanon' },
    // LC: { name: "Saint Lucia" },
    LI: { name: 'Liechtenstein' },
    LK: { name: 'Sri Lanka' },
    LR: { name: 'Liberia' },
    LS: { name: 'Lesotho' },
    LT: { name: 'Lithuania' },
    LU: { name: 'Luxembourg' },
    LV: { name: 'Latvia' },
    LY: { name: 'Libya' },
    MA: { name: 'Morocco' },
    MC: { name: 'Monaco' },
    MD: { name: 'Moldova' },
    ME: { name: 'Montenegro' },
    // MF: { name: "Saint Martin" },
    MG: { name: 'Madagascar' },
    MH: { name: 'Marshall Islands' },
    MK: { name: 'North Macedonia' },
    ML: { name: 'Mali' },
    MM: { name: 'Myanmar' },
    MN: { name: 'Mongolia' },
    MO: { name: 'Macau' },
    MP: { name: 'Northern Mariana Islands' },
    MQ: { name: 'Martinique' },
    MR: { name: 'Mauritania' },
    MS: { name: 'Montserrat' },
    MT: { name: 'Malta' },
    MU: { name: 'Mauritius' },
    MV: { name: 'Maldives' },
    MW: { name: 'Malawi' },
    MX: { name: 'Mexico' },
    MY: { name: 'Malaysia' },
    MZ: { name: 'Mozambique' },
    NA: { name: 'Namibia' },
    // NC: { name: "New Caledonia" },
    NE: { name: 'Niger' },
    NF: { name: 'Norfolk Island' },
    NG: { name: 'Nigeria' },
    NI: { name: 'Nicaragua' },
    NL: { name: 'Netherlands' },
    NO: { name: 'Norway' },
    NP: { name: 'Nepal' },
    NR: { name: 'Nauru' },
    NU: { name: 'Niue' },
    NZ: { name: 'New Zealand' },
    OM: { name: 'Oman' },
    PS: { name: 'Palestine' },
    PA: { name: 'Panama' },
    PE: { name: 'Peru' },
    PF: { name: 'French Polynesia' },
    PG: { name: 'Papua New Guinea' },
    PH: { name: 'Philippines' },
    PK: { name: 'Pakistan' },
    PL: { name: 'Poland' },
    PM: { name: 'Saint Pierre and Miquelon' },
    PR: { name: 'Puerto Rico' },
    PT: { name: 'Portugal' },
    PW: { name: 'Palau' },
    PY: { name: 'Paraguay' },
    QA: { name: 'Qatar' },
    // RE: { name: "Réunion" },
    RO: { name: 'Romania' },
    RS: { name: 'Serbia' },
    RU: { name: 'Russia' },
    RW: { name: 'Rwanda' },
    SA: { name: 'Saudi Arabia' },
    SB: { name: 'Solomon Islands' },
    SC: { name: 'Seychelles' },
    SD: { name: 'Sudan' },
    SE: { name: 'Sweden' },
    SG: { name: 'Singapore' },
    // SH: { name: "Saint Helena" },
    SI: { name: 'Slovenia' },
    // SJ: { name: "Svalbard and Jan Mayen" },
    SK: { name: 'Slovakia' },
    SL: { name: 'Sierra Leone' },
    SM: { name: 'San Marino' },
    SN: { name: 'Senegal' },
    SO: { name: 'Somalia' },
    SR: { name: 'Suriname' },
    SS: { name: 'South Sudan' },
    ST: { name: 'São Tomé and Príncipe' },
    SV: { name: 'El Salvador' },
    SX: { name: 'Sint Maarten' },
    SY: { name: 'Syria' },
    SZ: { name: 'Eswatini' },
    // TA: { name: "Tristan da Cunha" },
    TC: { name: 'Turks and Caicos Islands' },
    TD: { name: 'Chad' },
    TG: { name: 'Togo' },
    TH: { name: 'Thailand' },
    TJ: { name: 'Tajikistan' },
    TK: { name: 'Tokelau' },
    TL: { name: 'Timor-Leste' },
    TM: { name: 'Turkmenistan' },
    TN: { name: 'Tunisia' },
    TO: { name: 'Tonga' },
    TR: { name: 'Turkey' },
    TT: { name: 'Trinidad and Tobago' },
    TV: { name: 'Tuvalu' },
    TW: { name: 'Taiwan' },
    TZ: { name: 'Tanzania' },
    UA: { name: 'Ukraine' },
    UG: { name: 'Uganda' },
    US: { name: 'United States of America' },
    UY: { name: 'Uruguay' },
    UZ: { name: 'Uzbekistan' },
    // VA: { name: "Vatican City" },
    // VC: { name: "Saint Vincent and the Grenadines" },
    VE: { name: 'Venezuela' },
    VG: { name: 'British Virgin Islands' },
    VI: { name: 'United States Virgin Islands' },
    VN: { name: 'Vietnam' },
    VU: { name: 'Vanuatu' },
    // WF: { name: "Wallis and Futuna" },
    WS: { name: 'Samoa' },
    // XK: { name: "Kosovo" },
    YE: { name: 'Yemen' },
    // YT: { name: "Mayotte" },
    ZA: { name: 'South Africa' },
    ZM: { name: 'Zambia' },
    ZW: { name: 'Zimbabwe' },
} as const;

export const countryCodes = Object.keys(countryCodeData) as SupportedCountryCode[];
