export type KeyboardEventKey =
    | ' '
    | '_'
    | '-'
    | ';'
    | ':'
    | '!'
    | '?'
    | '.'
    | ''
    | '"'
    | '('
    | ')'
    | '['
    | ']'
    | '{'
    | '}'
    | '@'
    | '*'
    | '/'
    | '\\'
    | '&'
    | '#'
    | '%'
    | '`'
    | '^'
    | '+'
    | '<'
    | '='
    | '>'
    | '|'
    | '~'
    | '$'
    | '0'
    | '1'
    | '2'
    | '3'
    | '4'
    | '5'
    | '6'
    | '7'
    | '8'
    | '9'
    | 'A'
    | 'a'
    | 'Alt'
    | 'ArrowDown'
    | 'ArrowLeft'
    | 'ArrowRight'
    | 'ArrowUp'
    | 'AudioVolumeDown'
    | 'AudioVolumeMute'
    | 'AudioVolumeUp'
    | 'B'
    | 'b'
    | 'Backspace'
    | 'C'
    | 'c'
    | 'CapsLock'
    | 'ContextMenu'
    | 'Control'
    | 'D'
    | 'd'
    | 'Delete'
    | 'E'
    | 'e'
    | 'End'
    | 'Enter'
    | 'Escape'
    | 'F'
    | 'f'
    | 'F1'
    | 'F2'
    | 'F3'
    | 'F4'
    | 'F5'
    | 'F6'
    | 'F7'
    | 'F8'
    | 'F9'
    | 'F10'
    | 'F11'
    | 'F12'
    | 'G'
    | 'g'
    | 'H'
    | 'h'
    | 'Home'
    | 'I'
    | 'i'
    | 'Insert'
    | 'J'
    | 'j'
    | 'K'
    | 'k'
    | 'L'
    | 'l'
    | 'M'
    | 'm'
    | 'Meta'
    | 'N'
    | 'n'
    | 'NumLock'
    | 'O'
    | 'o'
    | 'P'
    | 'p'
    | 'PageDown'
    | 'PageUp'
    | 'Pause'
    | 'PrintScreen'
    | 'Q'
    | 'q'
    | 'R'
    | 'r'
    | 'S'
    | 's'
    | 'ScrollLock'
    | 'Shift'
    | 'T'
    | 't'
    | 'Tab'
    | 'U'
    | 'u'
    | 'V'
    | 'v'
    | 'W'
    | 'w'
    | 'X'
    | 'x'
    | 'Y'
    | 'y'
    | 'Z'
    | 'z'
    | "'";

export type KeyboardEventCodeCustom = 'Ctrl+Option+Space';

export type KeyboardEventCodeShift = `Shift+${KeyboardEventCodeBase}`;

export type KeyboardEventCode = KeyboardEventCodeBase | KeyboardEventCodeCustom | KeyboardEventCodeShift;

export type KeyboardEventCodeBase =
    | 'AltLeft'
    | 'AltRight'
    | 'ArrowDown'
    | 'ArrowLeft'
    | 'ArrowRight'
    | 'ArrowUp'
    | 'AudioVolumeDown'
    | 'AudioVolumeMute'
    | 'AudioVolumeUp'
    | 'Backquote'
    | 'Backslash'
    | 'Backspace'
    | 'BracketLeft'
    | 'BracketRight'
    | 'CapsLock'
    | 'Comma'
    | 'ContextMenu'
    | 'ControlLeft'
    | 'ControlRight'
    | 'Delete'
    | 'Digit0'
    | 'Digit1'
    | 'Digit2'
    | 'Digit3'
    | 'Digit4'
    | 'Digit5'
    | 'Digit6'
    | 'Digit7'
    | 'Digit8'
    | 'Digit9'
    | 'End'
    | 'Enter'
    | 'Equal'
    | 'Escape'
    | 'F1'
    | 'F2'
    | 'F3'
    | 'F4'
    | 'F5'
    | 'F6'
    | 'F7'
    | 'F8'
    | 'F9'
    | 'F10'
    | 'F11'
    | 'F12'
    | 'Home'
    | 'Insert'
    | 'KeyA'
    | 'KeyB'
    | 'KeyC'
    | 'KeyD'
    | 'KeyE'
    | 'KeyF'
    | 'KeyG'
    | 'KeyH'
    | 'KeyI'
    | 'KeyJ'
    | 'KeyK'
    | 'KeyL'
    | 'KeyM'
    | 'KeyN'
    | 'KeyO'
    | 'KeyP'
    | 'KeyQ'
    | 'KeyR'
    | 'KeyS'
    | 'KeyT'
    | 'KeyU'
    | 'KeyV'
    | 'KeyW'
    | 'KeyX'
    | 'KeyY'
    | 'KeyZ'
    | 'MetaLeft'
    | 'MetaRight'
    | 'Minus'
    | 'NumLock'
    | 'Numpad0'
    | 'Numpad1'
    | 'Numpad2'
    | 'Numpad3'
    | 'Numpad4'
    | 'Numpad5'
    | 'Numpad6'
    | 'Numpad7'
    | 'Numpad8'
    | 'Numpad9'
    | 'NumpadAdd'
    | 'NumpadDecimal'
    | 'NumpadDivide'
    | 'NumpadMultiply'
    | 'NumpadSubtract'
    | 'PageDown'
    | 'PageUp'
    | 'Pause'
    | 'Period'
    | 'PrintScreen'
    | 'Quote'
    | 'ScrollLock'
    | 'Semicolon'
    | 'ShiftLeft'
    | 'ShiftRight'
    | 'Slash'
    | 'Space'
    | 'Tab';

export const EVENT_KEY: Record<KeyboardEventKey, KeyboardEventKey> = {
    Backspace: 'Backspace',
    Tab: 'Tab',
    Enter: 'Enter',
    Shift: 'Shift',
    Control: 'Control',
    Alt: 'Alt',
    Pause: 'Pause',
    CapsLock: 'CapsLock',
    Escape: 'Escape',
    ' ': ' ',
    PageUp: 'PageUp',
    PageDown: 'PageDown',
    End: 'End',
    Home: 'Home',
    ArrowLeft: 'ArrowLeft',
    ArrowUp: 'ArrowUp',
    ArrowRight: 'ArrowRight',
    ArrowDown: 'ArrowDown',
    PrintScreen: 'PrintScreen',
    Insert: 'Insert',
    Delete: 'Delete',
    '0': '0',
    '1': '1',
    '2': '2',
    '3': '3',
    '4': '4',
    '5': '5',
    '6': '6',
    '7': '7',
    '8': '8',
    '9': '9',
    A: 'A',
    B: 'B',
    C: 'C',
    D: 'D',
    E: 'E',
    F: 'F',
    G: 'G',
    H: 'H',
    I: 'I',
    J: 'J',
    K: 'K',
    L: 'L',
    M: 'M',
    N: 'N',
    O: 'O',
    P: 'P',
    Q: 'Q',
    R: 'R',
    S: 'S',
    T: 'T',
    U: 'U',
    V: 'V',
    W: 'W',
    X: 'X',
    Y: 'Y',
    Z: 'Z',
    a: 'a',
    b: 'b',
    c: 'c',
    d: 'd',
    e: 'e',
    f: 'f',
    g: 'g',
    h: 'h',
    i: 'i',
    j: 'j',
    k: 'k',
    l: 'l',
    m: 'm',
    n: 'n',
    o: 'o',
    p: 'p',
    q: 'q',
    r: 'r',
    s: 's',
    t: 't',
    u: 'u',
    v: 'v',
    w: 'w',
    x: 'x',
    y: 'y',
    z: 'z',
    Meta: 'Meta',
    ContextMenu: 'ContextMenu',
    AudioVolumeMute: 'AudioVolumeMute',
    AudioVolumeDown: 'AudioVolumeDown',
    AudioVolumeUp: 'AudioVolumeUp',
    F1: 'F1',
    F2: 'F2',
    F3: 'F3',
    F4: 'F4',
    F5: 'F5',
    F6: 'F6',
    F7: 'F7',
    F8: 'F8',
    F9: 'F9',
    F10: 'F10',
    F11: 'F11',
    F12: 'F12',
    NumLock: 'NumLock',
    ScrollLock: 'ScrollLock',
    ';': ';',
    '=': '=',
    '': '',
    '-': '-',
    '.': '.',
    '/': '/',
    '`': '`',
    '[': '[',
    '\\': '\\',
    ']': ']',
    "'": "'",
    '~': '~',
    '!': '!',
    '@': '@',
    '#': '#',
    $: '$',
    '%': '%',
    '^': '^',
    '&': '&',
    '*': '*',
    '(': '(',
    ')': ')',
    _: '_',
    '+': '+',
    '{': '{',
    '}': '}',
    '|': '|',
    ':': ':',
    '"': '"',
    '<': '<',
    '>': '>',
    '?': '?',
} as const;
